name: Run Tests on Push
on:
  push:
    branches:
      - main

jobs:
  Tests:
    runs-on: ubuntu-latest
    environment: Kaggle

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set execute permissions for tests.sh
        run: |
          cd project
          chmod +x tests.sh

      - name: Run tests
        env:
          KAGGLE_USERNAME: ${{ secrets.USERNAME }}
          KAGGLE_KEY: ${{ secrets.KEY }}
        run: |
          cd project
          bash ./tests.sh
